package org.lasalle.recipeapp.ui.viewmodels

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.launch
import org.lasalle.recipeapp.data.services.KtorfitFactory
import org.lasalle.recipeapp.data.services.Preferences
import org.lasalle.recipeapp.models.Prompt
import org.lasalle.recipeapp.models.Recipe
import org.lasalle.recipeapp.models.RecipePreview

class HomeViewModel : ViewModel(){
    private val recipeService = KtorfitFactory.createRecipeService()
    var ingredients by mutableStateOf("")
    var generatedRecipe by mutableStateOf<RecipePreview?>(null)
    var recentRecipes by mutableStateOf<List<Recipe>>(listOf())
    var recipes by mutableStateOf<List<Recipe>>(listOf())
    var showSheet by mutableStateOf(false)
    val userId = Preferences.getUserId()
    var isLoading by mutableStateOf(false)
    var isGenerated by mutableStateOf(false)
    var userName by mutableStateOf("")

    init {
        loadRecipes()
        loadUser()
    }

    fun loadRecipes(){
        viewModelScope.launch {
            try {
                isLoading = true
                val result = recipeService.getRecipesByUserId(userId)
                recipes = result
                recentRecipes = recipes.takeLast(5).reversed()
                println("Recetas cargadas: ${result}")
            }catch (e: Exception){
                println("Error al cargar las recetas: ${e}")
            }
            finally {
                isLoading = false
            }
        }
    }

    fun generateRecipe(onShowSheet: ()->Unit){
        viewModelScope.launch {
            try {
                isLoading = true
                if (ingredients.isBlank()){
                    println("No se proporcionaron ingredientes.")
                    return@launch
                }
                val prompt = Prompt(
                    ingredients = ingredients
                )
                val result = recipeService.generateRecipe(prompt)
                generatedRecipe = result
                isGenerated = false
                showSheet = true
                println("Receta generada: ${result}")
            }catch (e: Exception){
                println("Error al generar la receta: ${e}")
            }
            finally {
                isLoading = false
            }
        }
    }
    fun showModalFromList(recipe: RecipePreview){
        showSheet = true
        generatedRecipe = recipe
        isGenerated = true
    }

    fun saveRecipeInDb(){
        viewModelScope.launch {
            val recipe = Recipe(
                id = 0,
                category = generatedRecipe?.category ?: "",
                imageUrl = generatedRecipe?.imageUrl ?: "",
                ingredients = generatedRecipe?.ingredients ?: listOf(),
                instructions = generatedRecipe?.instructions ?: listOf(),
                userId = userId,
                minutes = generatedRecipe?.minutes ?: 0,
                stars = generatedRecipe?.stars ?: 0,
                title = generatedRecipe?.title ?: ""

            )
            val result = recipeService.saveRecipeInDb(
                recipe
            )
//            showSheet = false
            loadRecipes()
        }
    }
    fun hidemodal(){
        showSheet = false
        generatedRecipe = null
        isGenerated = false
    }
    fun loadUser() {
        viewModelScope.launch {
            try {
                val response = KtorfitFactory.getAuthService().getUserId(userId)
                println("RESPONSE RAW: $response")
                println("RESPONSE TYPE: ${response::class.simpleName}")
                println("USER: ${response.user}")
                println("NAME: ${response.user.name}")
                userName = response.user.name
                println("Usuario cargado: $userName")
            } catch (e: Exception) {
                println("Error al cargar usuario: $e")
            }
        }
    }

    fun logout(){
        Preferences.clearPreferences()
        isLoading = false
        ingredients = ""
        generatedRecipe = null
        recentRecipes = listOf()
        recipes = listOf()
        showSheet = false
        userName = ""
    }
}